[
  {"canBook":true,"company_name":"","business_no":0,"allow_cancel":true,"visibility_scope":"","visibility":"public","cancel_cutoff":30,"allow_transfer":false,"category_name":"General","details":{"products":[],"keywords":[],"trackers":[],"keyword_actions":[],"point_activities":[],"notifications":[],"totalViews":0,"campaigns":[]},"totalAttendees":6,"totalPending":0,"totalUsed":0,"totalUnused":6,"event_timezone":0,"survey_no":0,"attendees":[],"tickets":[],"share_long":"","share_short":"","stats":[{"name":"register","value":6}],"business_location_no":0,"media":[{"reference_id":"","main":"N","media_no":112909,"media_title":"Event Flyer - mHUB Information Session with The Autonomous Vehicle Alliance","media_description":"Event Flyer","media_location":"https://peoplevine.blob.core.windows.net/media/397/39788b2511a-6b6a-4bae-8074-8b07a4990214.png","media_type":"image","company_no":397,"reference_type":"event","reference_no":4180,"created_on":"/Date(1498846815753)/","totalFavorite":0,"skipTriggers":false,"includeObjects":false,"includeStats":false,"includeTotalRecords":false,"totalRecords":0,"rows_per_page":0,"page_number":0,"updateFields":"","includeCompany":false,"lightweight":false,"itemDetailsFields":null,"includeItemDetails":false,"search_value":null,"sort_by":null,"return_total":0,"from_date":"/Date(-2208988800000)/","to_date":"/Date(-2208988800000)/","includeDetails":false,"timezone_offset":0,"timezone_id":null},{"reference_id":"","main":"Y","media_no":112908,"media_title":"Event Flyer - mHUB Information Session with The Autonomous Vehicle Alliance","media_description":"Event Flyer","media_location":"https://peoplevine.blob.core.windows.net/media/397/39771831e20-885b-4654-b539-7d360d97a572.png","media_type":"image","company_no":397,"reference_type":"event","reference_no":4180,"created_on":"/Date(1498846695810)/","totalFavorite":0,"skipTriggers":false,"includeObjects":false,"includeStats":false,"includeTotalRecords":false,"totalRecords":0,"rows_per_page":0,"page_number":0,"updateFields":"","includeCompany":false,"lightweight":false,"itemDetailsFields":null,"includeItemDetails":false,"search_value":null,"sort_by":null,"return_total":0,"from_date":"/Date(-2208988800000)/","to_date":"/Date(-2208988800000)/","includeDetails":false,"timezone_offset":0,"timezone_id":null}],"event_no":4180,"repeat_frequency":"","event_id":"","event_title":"mHUB and New Mobility Lab Information Session with The Autonomous Vehicle Alliance","event_description":"\u003cp class=\"p1\"\u003e\u003cspan class=\"s1\"\u003eThe Autonomous Vehicle Alliance\u0026nbsp;uniquely focuses on the identification of\u0026nbsp;consumer and customer facing value propositions associated\u0026nbsp;with Level 4 and 5 autonomous vehicles.\u0026nbsp;\u003c/span\u003e\u003c/p\u003e\n\u003cp class=\"p1\"\u003e\u003cspan class=\"s1\"\u003eTim Woods, General Manager of the AVA,\u0026nbsp;will be here\u0026nbsp;to share the topline collaborative research being conducted\u0026nbsp;by General Motors, Ford Motor Company, FCA, All State, Cox Automotive, Magna International, Spartan Motors and The Taubman Company. In particular, Tim will review and answer questions from the AVA's Fleet Ecosystem Needs Assessment Research, The Global Longitudinal Consumer Perceptions Study and the recently completed Municipal Research. He will also share upcoming research in development by the AVA and it's significance to the evolving\u0026nbsp;autonomous ecosystem. \u0026nbsp;\u003c/span\u003e\u003c/p\u003e","event_summary":"Tim Woods, General Manager of the AVA, will visit mHUB to share the topline collaborative research being conducted by General Motors, Ford Motor Company, FCA, All State, Cox Automotive, Magna International, Spartan Motors and The Taubman Company. Tim will review and answer questions from the AVA's Fleet Ecosystem Needs Assessment Research, The Global Longitudinal Consumer Perceptions Study and the recently completed Municipal Research.","event_date":"/Date(1499781600000)/","event_date_end":"/Date(1499787000000)/","event_repeat":0,"event_duration":-1060589640,"event_location":"965 West Chicago Avenue, Chicago, IL, United States","event_type":"register","event_display":"public","company_no":397,"user_no":0,"created_on":"/Date(1498846130480)/","event_timezone_id":"Central Standard Time","event_venue":"mHUB Classroom","event_graphic":"https://peoplevine.blob.core.windows.net/media/397/39788b2511a-6b6a-4bae-8074-8b07a4990214.png","category_no":0,"event_keyword":"E639704180","template_no":0,"event_status":"approved","external_link":"","event_hashtag":"","event_data":"","facebook_link":"","meta_keywords":"","meta_description":"","totalFavorite":0,"skipTriggers":false,"includeObjects":false,"includeStats":false,"includeTotalRecords":false,"totalRecords":0,"rows_per_page":0,"page_number":0,"updateFields":"","includeCompany":false,"lightweight":false,"itemDetailsFields":null,"includeItemDetails":false,"search_value":null,"sort_by":null,"return_total":0,"from_date":"/Date(-2208988800000)/","to_date":"/Date(-2208988800000)/","includeDetails":false,"timezone_offset":0,"timezone_id":null}
]

// filtered attributes (present? and != 0)

// {"canBook"=>true,
//  "allow_cancel"=>true,
//  "visibility"=>"public",
//  "cancel_cutoff"=>30,
//  "category_name"=>"General",
//  "details"=>
//   {"products"=>[],
//    "keywords"=>[],
//    "trackers"=>[],
//    "keyword_actions"=>[],
//    "point_activities"=>[],
//    "notifications"=>[],
//    "totalViews"=>0,
//    "campaigns"=>[]},
//  "totalAttendees"=>6,
//  "totalUnused"=>6,
//  "stats"=>[{"name"=>"register", "value"=>6}],
//  "media"=>
//   [{"reference_id"=>"",
//     "main"=>"N",
//     "media_no"=>112909,
//     "media_title"=>
//      "Event Flyer - mHUB Information Session with The Autonomous Vehicle Alliance",
//     "media_description"=>"Event Flyer",
//     "media_location"=>
//      "https://peoplevine.blob.core.windows.net/media/397/39788b2511a-6b6a-4bae-8074-8b07a4990214.png",
//     "media_type"=>"image",
//     "company_no"=>397,
//     "reference_type"=>"event",
//     "reference_no"=>4180,
//     "created_on"=>"/Date(1498846815753)/",
//     "totalFavorite"=>0,
//     "skipTriggers"=>false,
//     "includeObjects"=>false,
//     "includeStats"=>false,
//     "includeTotalRecords"=>false,
//     "totalRecords"=>0,
//     "rows_per_page"=>0,
//     "page_number"=>0,
//     "updateFields"=>"",
//     "includeCompany"=>false,
//     "lightweight"=>false,
//     "itemDetailsFields"=>nil,
//     "includeItemDetails"=>false,
//     "search_value"=>nil,
//     "sort_by"=>nil,
//     "return_total"=>0,
//     "from_date"=>"/Date(-2208988800000)/",
//     "to_date"=>"/Date(-2208988800000)/",
//     "includeDetails"=>false,
//     "timezone_offset"=>0,
//     "timezone_id"=>nil},
//    {"reference_id"=>"",
//     "main"=>"Y",
//     "media_no"=>112908,
//     "media_title"=>
//      "Event Flyer - mHUB Information Session with The Autonomous Vehicle Alliance",
//     "media_description"=>"Event Flyer",
//     "media_location"=>
//      "https://peoplevine.blob.core.windows.net/media/397/39771831e20-885b-4654-b539-7d360d97a572.png",
//     "media_type"=>"image",
//     "company_no"=>397,
//     "reference_type"=>"event",
//     "reference_no"=>4180,
//     "created_on"=>"/Date(1498846695810)/",
//     "totalFavorite"=>0,
//     "skipTriggers"=>false,
//     "includeObjects"=>false,
//     "includeStats"=>false,
//     "includeTotalRecords"=>false,
//     "totalRecords"=>0,
//     "rows_per_page"=>0,
//     "page_number"=>0,
//     "updateFields"=>"",
//     "includeCompany"=>false,
//     "lightweight"=>false,
//     "itemDetailsFields"=>nil,
//     "includeItemDetails"=>false,
//     "search_value"=>nil,
//     "sort_by"=>nil,
//     "return_total"=>0,
//     "from_date"=>"/Date(-2208988800000)/",
//     "to_date"=>"/Date(-2208988800000)/",
//     "includeDetails"=>false,
//     "timezone_offset"=>0,
//     "timezone_id"=>nil}],
//  "event_no"=>4180,
//  "event_title"=>
//   "mHUB and New Mobility Lab Information Session with The Autonomous Vehicle Alliance",
//  "event_description"=>
//   "<p class=\"p1\"><span class=\"s1\">The Autonomous Vehicle Alliance&nbsp;uniquely focuses on the identification of&nbsp;consumer and customer facing value propositions associated&nbsp;with Level 4 and 5 autonomous vehicles.&nbsp;</span></p>\n<p class=\"p1\"><span class=\"s1\">Tim Woods, General Manager of the AVA,&nbsp;will be here&nbsp;to share the topline collaborative research being conducted&nbsp;by General Motors, Ford Motor Company, FCA, All State, Cox Automotive, Magna International, Spartan Motors and The Taubman Company. In particular, Tim will review and answer questions from the AVA's Fleet Ecosystem Needs Assessment Research, The Global Longitudinal Consumer Perceptions Study and the recently completed Municipal Research. He will also share upcoming research in development by the AVA and it's significance to the evolving&nbsp;autonomous ecosystem. &nbsp;</span></p>",
//  "event_summary"=>
//   "Tim Woods, General Manager of the AVA, will visit mHUB to share the topline collaborative research being conducted by General Motors, Ford Motor Company, FCA, All State, Cox Automotive, Magna International, Spartan Motors and The Taubman Company. Tim will review and answer questions from the AVA's Fleet Ecosystem Needs Assessment Research, The Global Longitudinal Consumer Perceptions Study and the recently completed Municipal Research.",
//  "event_date"=>"/Date(1499781600000)/",
//  "event_date_end"=>"/Date(1499787000000)/",
//  "event_duration"=>-1060589640,
//  "event_location"=>"965 West Chicago Avenue, Chicago, IL, United States",
//  "event_type"=>"register",
//  "event_display"=>"public",
//  "company_no"=>397,
//  "created_on"=>"/Date(1498846130480)/",
//  "event_timezone_id"=>"Central Standard Time",
//  "event_venue"=>"mHUB Classroom",
//  "event_graphic"=>
//   "https://peoplevine.blob.core.windows.net/media/397/39788b2511a-6b6a-4bae-8074-8b07a4990214.png",
//  "event_keyword"=>"E639704180",
//  "event_status"=>"approved",
//  "from_date"=>"/Date(-2208988800000)/",
//  "to_date"=>"/Date(-2208988800000)/"}
